### ISSUE TITLE
Sound indicator shows melody as not playing, despite playing music

### ISSUE THREAD

**Issue by yerbestpal** [artemanufrij/playmymusic#140] opened 2018-10-19 10:07 UTC
![screenshot from 2018-10-19 11-04-23](https://user-images.githubusercontent.com/15250241/47212070-1c193c00-d38f-11e8-8980-ccdbd0eb1e62.png)

**Comment by artemanufrij** [comment] 2018-10-19 10:32
@yerbestpal thanks for feedback I will check it as soon as possible!

**Comment by artemanufrij** [comment] 2018-10-19 11:36
@yerbestpal I can't reproduce it on my system:
![screenshot von 2018-10-19 13 35 33](https://user-images.githubusercontent.com/16517095/47216050-f21e4480-d3a3-11e8-8bfa-9141dbc23fea.png)

**Comment by yerbestpal** [comment] 2018-10-19 11:39
Strange. Are you using Juno?

**Comment by artemanufrij** [comment] 2018-10-19 11:40
yes

**Comment by artemanufrij** [comment] 2018-10-19 11:41
![screenshot von 2018-10-19 13 40 51](https://user-images.githubusercontent.com/16517095/47216259-9f915800-d3a4-11e8-9ab6-3d989bc9edd1.png)

**Comment by yerbestpal** [comment] 2018-10-19 11:42
Hrm. Unfortunately I am not a developer so I am very limited as far as diagnosing any issues is concerned.

**Comment by artemanufrij** [comment] 2018-10-19 11:48
@yerbestpal no problem. What happens if you use the buttons inside the widget?

**Comment by yerbestpal** [comment] 2018-10-19 12:34
Okay, I can no longer reproduce the bug.

**Comment by artemanufrij** [comment] 2018-10-19 17:42
Can I close this issue?

**Comment by yerbestpal** [comment] 2018-10-19 18:55
I think so. If it occurs again I'll be sure to mention.

**Closed** 2018-10-19 19:07 UTC
