### ISSUE TITLE
Cannot set as default application for Music

### ISSUE THREAD

**Issue by ayoisaiah** [artemanufrij/playmymusic#31] opened 2017-10-24 09:56 UTC
It appears that the app cannot be set at the default Music App at this time. It doesn't show up on the list in the Settings

![image](https://user-images.githubusercontent.com/13372163/31936579-e271ebce-b8a9-11e7-8170-c5d4c50d2c12.png)

**Comment by ayoisaiah** [comment] 2017-10-25 21:33
@artemanufrij Well it seems to be a problem on my machine. The option does not appear

**Comment by artemanufrij** [comment] 2017-10-25 21:41
@ayoisaiah are you on elementary 0.4.1?

**Comment by ayoisaiah** [comment] 2017-10-25 21:55
@artemanufrij Yes, everything up to date

**Comment by artemanufrij** [comment] 2017-10-25 22:01
@ayoisaiah what about `right click` on a music file -> `open with` -> `other apps` ->
![bildschirmfoto von 2017-10-25 23 59 42](https://user-images.githubusercontent.com/16517095/32025505-c54ab3ae-b9e0-11e7-808e-8dee5672078b.png)

**Comment by ayoisaiah** [comment] 2017-10-26 04:59
@artemanufrij Oh yes it appears on that list, and setting it as default works as expected. But it's still not reflected in the settings

**Comment by artemanufrij** [comment] 2018-02-23 21:45
I'm going to close this issue, because I can't reproduce this issue. I tried it on >5 different systems and it worked an all them.

**Closed by artemanufrij** 2018-02-23 21:45 UTC
