### ISSUE TITLE
Error opening directory "too many files open"

### ISSUE THREAD

**Issue by ghoppaccia** [artemanufrij/playmymusic#28] opened 2017-10-19 18:32 UTC
Program crashes for some reason, getting this message in terminal

** (com.github.artemanufrij.playmymusic:27850): WARNING **: LocalFilesManager.vala:81: Error opening directory '_directory here_' : Too many files open

**Comment by artemanufrij** [comment] 2017-10-19 18:35
@ghoppaccia thank you for your feedback.

How many files do you have in your library?

**Comment by ghoppaccia** [comment] 2017-10-19 18:41
mmh don't know actually, but a lot. It's a 46.2 Gb Music library

**Comment by artemanufrij** [comment] 2017-10-22 08:51
@ghoppaccia you are welcome. I'm going to check it next days

**Comment by artemanufrij** [comment] 2017-11-04 18:36
@ghoppaccia could you test it with last release please?

**Comment by ghoppaccia** [comment] 2017-11-07 15:59
Tried yesterday and at first it was working, then after a while, while it was still adding music files, I got a segmentation fault. 
Don't know if i did something else that might have conflicted, but I'll try again today and see what happens.
Thanks!

**Comment by ghoppaccia** [comment] 2017-11-07 16:05
That's funny, now first time opened it crashed with this error:
(com.github.artemanufrij.playmymusic:4711): GLib-ERROR **: Creating pipes for GWakeup: Too many files open

Trace/breakpoint trap (core dumped).

Then tried again and got once again the "Segmentation error (core dumped)"

And now, third time opened seems to be working, still adding music to library.

**Comment by artemanufrij** [comment] 2017-11-07 17:59
how much file were imported before it crached?

**Comment by ghoppaccia** [comment] 2017-11-07 18:02
Mhhh I'm not sure about that unfortunately. I remember a number around 6.500, but that was the number on the side of the filenames in terminal, I'm not sure if it refers to the total of files in the library or if it's juste the ones imported in that "session" of the app.

**Comment by artemanufrij** [comment] 2017-11-07 18:03
yes, I mean the ID....

how is it mounted? Samba or NFS?

**Comment by ghoppaccia** [comment] 2017-11-07 18:29
Just a normal folder, I only have my /home on a separate partition (in the same HDD)

**Comment by artemanufrij** [comment] 2017-11-24 16:43
@ghoppaccia can you reproduce this issue with current version?

**Comment by artemanufrij** [comment] 2018-01-22 16:24
I'm going to close it. I can't reproduce it anymore.

**Closed by artemanufrij** 2018-01-22 16:24 UTC
Labels: ready for test
